name: Tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['8.1', '8.2', '8.3']
        laravel: ['10.*', '11.*', '12.*']
        exclude:
          - php: '8.1'
            laravel: '11.*'
          - php: '8.1'
            laravel: '12.*'

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite3, pdo_sqlite, bcmath, soap, intl, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Execute tests
        run: vendor/bin/phpunit
